### ISSUE TITLE
undefined method `make_bootstrap_mail' for ...

### ISSUE THREAD

**Issue by Andreas045** [bootstrap-email/bootstrap-email#82]
After updating to 0.3.3, i get Exceptions when trying to send e-mails:

"undefined method `make_bootstrap_mail' for..."

(Rails 5.2.4.4 project)

**Comment by stuyam** [comment]
Just pushed v0.3.4 that should fix that. Let me know 👍

**Comment by Andreas045** [comment]
Thanks, everything is going perfectly now.
